name: ip-neighbor-notifications
version: '0.1.0.0'
synopsis: View AMQP messages.
description: Please see README.md
category: System
license: BSD3
homepage: http://github.com/name/project
ghc-options:
- -threaded
- -Wall
- -O2
dependencies:
- base
- amqp
- bytestring
- optparse-applicative
- text
- utf8-string
executables:
  amqp-tail:
    main: Main.hs
    source-dirs: src
